fprintf("Mencari nilai maximum")
[x max] = fminbnd(@(x) - (3*x.^3 + 9*x^2 + 28), -2, 0)
fprintf('================================\n')
fprintf("Mencari nilai minimum")
[x min] = fminbnd(@(x) (3*x.^3 + 9*x^2 + 28), -2, 0)
fprintf('================================\n')
fprintf("Grafik / Plot")
fplot(@(x)3*x.^3 + 9*x.^2 + 28, [-2, 0])
xlabel('x')
ylabel('y')